
jobs:
  - job:
    condition: succeeded()
    strategy:
      maxParallel: 2
      matrix:
        'Windows':
          os: vs2017-win2016
        'Linux':
          os: ubuntu-16.04
    pool:
      vmImage: $(os)
    steps:
      - checkout: self
        clean: all
      - task: NodeTool@0
        displayName: 'Install Node 10.15.x'
        inputs:
          versionSpec: 10.15.0
          checkLatest: true
      - script: node ./common/scripts/install-run-rush.js install
        displayName: Rush install
      - script: node ./common/scripts/install-run-rush.js build
        displayName: Rush build
      - script: node ./common/scripts/install-run-rush.js test:integration -v
        displayName: Rush Integration Test
